### ISSUE TITLE
Rmd support

### ISSUE THREAD

**Issue by maxheld83** [christophergandrud/language-knitr#1]
... would be fantastic, so we can have syntax highlighting for R inside (r)Markdown documents.
Maybe as part of / in conjunction with [Pandoc-flavored Markdown](https://atom.io/packages/language-pfm), then we'd have all the RMarkdown pieces together.

**Comment by christophergandrud** [comment]
Definitely a good idea. :+1:

**Comment by HenrikEckermann** [comment]
absolutely, please add knitr support for rmd if possible. And it would be great if it would also work with the style used in RStudio (at least if that is necessary so that we can also just open .rmd files someone wrote in Rstudio (not sure how flexible knitr is when it comes to leaving out the curly brackets)).
Thanks a lot for knitr support already!

**Comment by christophergandrud** [comment]
R Markdown support is provided in the [language-markdown](https://github.com/burodepeper/language-markdown) package. This package just has the old Sweave-style knitr syntax highlighting.
